language: node_js

node_js:
  - "8"

script:
  - npm run test && npm run build

deploy:
  provider: pages

  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true

  local-dir: public
  target-branch: gh-pages

  on:
    branch: master